### ISSUE TITLE
В десктопной версии параметр scope обязательный при запросе авторизации

### ISSUE THREAD

**Issue by idbolshakov** [VKCOM/vkui-connect#2]
https://vk.com/dev/vk_connect_events?f=6.%20%D0%90%D0%B2%D1%82%D0%BE%D1%80%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F%20%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D1%82%D0%B5%D0%BB%D1%8F

судя по документации `scope` не является обзяательным, в iOS и Android запрос на авторизацию проходит без него

в десктопе приходит ошибка, что отсутствует обязательный параметр `scope`.

---

Кажется, что нужно либо обновить документацию, либо пофиксить десктоп

**Comment by kuhel** [comment]
Привет, это не баг данного пакета. Уже исправлено на стороне VK.
