### ISSUE TITLE
Где можно посмотреть список всех событий?

### ISSUE THREAD

**Issue by mahnunchik** [VKCOM/vkui-connect#4]
События `VKWebAppEnableSwipeBack/VKWebAppDisableSwipeBack` нигде нормально не задокументированы и упомянаются только в примере кода https://vkcom.github.io/vkui-styleguide/#view

В продолжение тикета: https://github.com/VKCOM/VKUI/issues/229

Возможно есть что то подобное для Android.

**Comment by kuhel** [comment]
Привет, посмотри тут https://vk.com/dev/vk_connect_events
