### ISSUE TITLE
Как выглядит минимальное приложение?

### ISSUE THREAD

**Issue by MarisKori** [VKCOM/vkui-connect#5]
Подключаю этот код из vkui-connect, но connect.send всё равно не работает на телефонах.
Где можно посмотреть код готового минимального приложения типа Hello World?

**Comment by kuhel** [comment]
Привет,

https://www.npmjs.com/package/@vkontakte/create-vk-mini-app
https://github.com/kuhel/vk-ui-sample-vk-app
